databases:
  - name: t_guru
    databaseName: gur_8vvb
    user: gur_8vvb_user

services:
  - type: web
    name: test1
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
