databases:
  - name: test_guru
    databaseName: test_guru_nmzo
    user: test_guru_nmzo_user

services:
  - type: web
    name: test_guru
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_guru
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
